name: 'Laravel Build and Deploy'
description: 'Greet someone'
inputs:
  node-version:
    description: 'Version Node.js'
    required: false
    default: '16.x'
  php-version:
    description: 'Version PHP'
    required: false
    default: '7.4'
  cache-dependency-path:
    description: 'Cache dependency path'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - name: Install rsync
      run: sudo apt-get install rsync openssh-client -y
      shell: bash

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: mbstring, mongodb-1.12.0, random
        tools: composer

    - name: Setup Front-end
      run: make setup-front-end
      shell: bash

    - name: Build Front-end
      run: make build-front-end
      shell: bash

    - name: Setup Back-end
      run: make setup-back-end
      shell: bash

    - name: Build Back-end
      run: make build-back-end
      shell: bash

    - name: Deploy
      run: make deploy
      shell: bash
